project:
  type: website

website:
  title: "G2-Group12"
  navbar:
    left: 
      - href: overview.qmd
        text: Overview
      - href: proposal.qmd
        text: Project Propsal
      - href: poster.qmd
        text: Poster
      - href: methodology.qmd
        text: Methodology
      - href: report.qmd
        text: Report
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

