---
title: "Literature Review"
editor: visual
---

In this project, the following articles were referenced to in order to perform our analysis and better understand the situation of the junior college mergers:

|     |                                                                                                                                                                               **Title with Link**                                                                                                                                                                               |        **Type**       |
|:---:|:------------------------------------------:|:---------------------:|
|  1  |                                                                                                                                     [School mergers 2019: Why were the 8 government JCs the ones selected for merger?](https://str.sg/3nRk)                                                                                                                                     |     News Article      |
|  2  |                                                                                                                           [4 pairs of JCs to merge as student numbers shrink; 14 primary and 6 secondary schools also affected](https://str.sg/3gsL)                                                                                                                            |     News Article      |
|  3  |                                                                                                                                                          [School mergers 2019: 7 things to know](https://str.sg/3XRq)                                                                                                                                                           |     News Article      |
|  4  |                                                                                                                   [Why is the Ministry of Education merging some schools?](https://www.gov.sg/article/why-is-the-ministry-of-education-merging-some-schools)                                                                                                                    |  Government Article   |
|  5  |                                                                                                          [School mergers: More questions than answers](https://lkyspp.nus.edu.sg/docs/default-source/ips/td_school-mergers-more-questions-than-answers_250417-pdf.pdf)                                                                                                          |    Opinion Article    |
|  6  |                                                                                                           [Names of Junior Colleges Merging in 2019](https://lkyspp.nus.edu.sg/docs/default-source/ips/td_school-mergers-more-questions-than-answers_250417-pdf.pdf)                                                                                                            |     Press Release     |
|  7  |                                                                                                                            [URA to cut Anderson Serangoon JC\'s land area by a third as MOE considers building taller schools](https://str.sg/wjS6)                                                                                                                             |     News Article      |
|  8  |                                                                                                                              [Junior Colleges and Millennia Institute](https://www.moe.gov.sg/schoolfinder/?journey=Post%20secondary-JC%20school)                                                                                                                               | MOE School Catalougue |
|  9  |                                                                                                               [Construction, upgrading at some schools to be delayed](https://tnp.straitstimes.com/news/singapore/construction-upgrading-some-schools-be-delayed)                                                                                                               |     News Article      |
| 10  |                                                                                                                                                   [The importance of sleep](https://www.healthhub.sg/live-healthy/510/sleep)                                                                                                                                                    |  Government Article   |
| 11  |                                                                                                                                              [Financial Assistance](https://www.moe.gov.sg/financial-matters/financial-assistance)                                                                                                                                              |      Infographic      |
| 12  |                                                                                                                                     [Student Concessionary Fares](https://www.transitlink.com.sg/travel-fares/student-concessionary-fares/)                                                                                                                                     |      Infographic      |
| 13  |                                                                                                                             [School Smartcard/Non-MOE School Smartcard](https://www.transitlink.com.sg/school-smartcard-non-moe-school-smartcard/)                                                                                                                              |      Infographic      |
| 14  |                                                                                                                           [Household income from work for poor families in Singapore fell 69% last year due to Covid-19: Study](https://str.sg/JrEK)                                                                                                                            |     News Article      |
| 15  | [HDB prices heatmap](https://www.srx.com.sg/heat-map/?link=heatMap&mapView=true&propertyType=81&district=0&hdbTown=0&keywords=&postal=0&radius=0&projectsTabIndex=0&nearbyTabsIndex=0&pageIndex=0&teamId=&agentId=&locationSearch=true&selectedDistricts=0&selectedHdbTowns=0&selectedMrts=0&maxSale=0&maxRent=0&minSize=0&bedroom=0&propertySubtype=0&sortBy=volume&show=true) |      Infographic      |
